/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitorgui;
import com.fazecast.jSerialComm.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import koneksi_db_comm.*;
import javax.swing.JOptionPane;
import tools.FungsiQuery;
import tools.LogReport;
import tools.Vardump;

/**
 *
 * @author Anggun Dwiguna
 */
public class AuthorPage extends javax.swing.JFrame {

    /**
     * Creates new form AuthorPage
     */
    int start = 0;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    ArrayList<Vardump> yes = new ArrayList();
    ArrayList<Vardump> no = new ArrayList();
    ArrayList<Vardump> combo = new ArrayList();
    String nama_admin;
    
    public AuthorPage() {
        koneksi_db.config();
        con = koneksi_db.con;
        stat = koneksi_db.stm;
        initComponents();
        getRole();
        refreshList();
    }
    
    public void getNamaAdmin(String admin){
        nama_admin = admin;
    }
    
    void refreshList(){
        if(!yes.isEmpty()){
            yes.clear();
        }
        if(!no.isEmpty()){
            no.clear();
        }
        
        try{
            //seleksi daftar kiri
            rs = new FungsiQuery().selectData("*", "daftar_hakakses JOIN daftar_ruangan USING(id_ruangan)", "id_role='"+
                    combo.get(this.roleCombo.getSelectedIndex()).getId()+ "'");
            DefaultListModel dlml = new DefaultListModel();
            while(rs.next()){
                dlml.addElement(rs.getString("nama_ruangan"));
                Vardump r = new Vardump();
                r.setData(rs.getString("id_ruangan"), rs.getString("nama_ruangan"));
                yes.add(r);
            }
            trueList.setModel(dlml);
            
            //seleksi daftar kanan
            rs = new FungsiQuery().selectData("*", "daftar_ruangan", "`id_ruangan` NOT IN(" + "SELECT id_ruangan FROM daftar_hakakses WHERE id_role ='"+
                    combo.get(this.roleCombo.getSelectedIndex()).getId()+"')");
            DefaultListModel dlmr = new DefaultListModel();
            while(rs.next()){
                dlmr.addElement(rs.getString("nama_ruangan"));
                Vardump r = new Vardump();
                r.setData(rs.getString("id_ruangan"), rs.getString("nama_ruangan"));
                no.add(r);
            }
            falseList.setModel(dlmr);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void getRole(){        
        try{
            sql = "SELECT * FROM daftar_role";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                roleCombo.addItem(rs.getString("nama_role"));
                Vardump c = new Vardump();
                c.setData(rs.getString("id_role"), rs.getString("nama_role"));
                combo.add(c);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void refresh(){
        refreshList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roleCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        trueList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        falseList = new javax.swing.JList<>();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Manage Hak Akses");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lihat Daftar Autorisasi Role"));

        jLabel1.setText("Pilih Role");

        roleCombo.setPreferredSize(new java.awt.Dimension(95, 30));
        roleCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                roleComboItemStateChanged(evt);
            }
        });
        roleCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleComboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roleComboMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roleComboMouseReleased(evt);
            }
        });
        roleCombo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                roleComboComponentHidden(evt);
            }
        });
        roleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboActionPerformed(evt);
            }
        });

        trueList.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruangan Terautorisasi"));
        jScrollPane1.setViewportView(trueList);

        falseList.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruangan Tidak Terautorisasi"));
        jScrollPane2.setViewportView(falseList);

        removeButton.setText("Hapus Autorisasi =>");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        addButton.setText("<= Tambah Autorisasi");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeButton)
                    .addComponent(addButton))
                .addGap(18, 18, 18))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ROLE MANAGEMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        String id_ruangan = yes.get(this.trueList.getSelectedIndex()).getId();
        if(!this.trueList.isSelectionEmpty()){
            new FungsiQuery().deleteData("daftar_hakakses", "id_role = '" + combo.get(this.roleCombo.getSelectedIndex()).getId()+"' AND id_ruangan='"
                + id_ruangan +"'");
            new LogReport().report("RMAUTH", nama_admin, roleCombo.getSelectedItem().toString(), id_ruangan);
            refreshList();
        }        
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String id_ruangan = no.get(this.falseList.getSelectedIndex()).getId();
        if(!this.falseList.isSelectionEmpty()){
            new FungsiQuery().addData("daftar_hakakses", "`kode_ikat`, `id_role`, `id_ruangan`", "'"+
                    combo.get(this.roleCombo.getSelectedIndex()).getId()+ "-" + no.get(this.falseList.getSelectedIndex()).getId()+
                "', '" + combo.get(this.roleCombo.getSelectedIndex()).getId() +"', '" + id_ruangan + "'");
            new LogReport().report("ADDAUTH", nama_admin, roleCombo.getSelectedItem().toString(), id_ruangan);
            refreshList();
        }                
    }//GEN-LAST:event_addButtonActionPerformed
   
    private void roleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboActionPerformed
        // TODO add your handling code here  
        if(start > 0){
//            System.out.println("memulai refresh");
            refreshList();
        }
        start++;
    }//GEN-LAST:event_roleComboActionPerformed
    
    private void roleComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_roleComboItemStateChanged
        // TODO add your handling code here:                
    }//GEN-LAST:event_roleComboItemStateChanged

    private void roleComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboMouseClicked

    private void roleComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleComboMousePressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_roleComboMousePressed

    private void roleComboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleComboMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboMouseReleased

    private void roleComboComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_roleComboComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboComponentHidden
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JList<String> falseList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeButton;
    private javax.swing.JComboBox<String> roleCombo;
    private javax.swing.JList<String> trueList;
    // End of variables declaration//GEN-END:variables
}
