/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitorgui;
import Bfish.Blowfish;
import com.fazecast.jSerialComm.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import koneksi_db_comm.*;
import tools.*;

/**
 *
 * @author Anggun Dwiguna
 */
public class HomePage extends javax.swing.JFrame {
    /**
     * Creates new form HomePage
     */
    //menampung daftar port terdeteksi
    SerialPort port;
    SerialPort daftarPort[] = port.getCommPorts();
    ArrayList<Vardump> comm = new ArrayList();
    ArrayList<Vardump> role = new ArrayList();
    
    SerialConn serial = new SerialConn(null);
    String readData="";
    String nama_admin;
    ResultSet rs;
    
    public HomePage(String admin) {
        initComponents();
        showTime();
        showDate();
        koneksi_db.config();
        nama_admin = admin;
        
        //menampilkan daftar port dalam combo box
        for(SerialPort namaPort: daftarPort){
            portCombo.addItem(namaPort.getDescriptivePortName());
            Vardump c = new Vardump();
            c.setData("", namaPort.getSystemPortName());
            comm.add(c);
        }
        refreshList();
    }

    private HomePage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void refreshList(){
        //menampilkan daftar role dalam combo box                
        role.clear();
        roleCombo.removeAllItems();
        
        try{
            rs = new FungsiQuery().selectData("*", "daftar_role", "1");
            while(rs.next()){
                Vardump r = new Vardump();
                r.setData(rs.getString("id_role"), rs.getString("nama_role"));
                role.add(r);
                roleCombo.addItem(r.getData());
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timeLabel.setText(s.format(d));
            }
        }).start(); 
    }
    
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MMMM-yyyy");
        dateLabel.setText(s.format(d));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        portCombo = new javax.swing.JComboBox<>();
        connectButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        signButton = new javax.swing.JButton();
        roleCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        namaText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NUIDText = new javax.swing.JTextField();
        scanButton = new javax.swing.JButton();
        identitasText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dumpButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        authorButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        roleButton = new javax.swing.JButton();
        taglistButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        statusButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        scanButton2 = new javax.swing.JButton();
        NUIDText2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DASHBOARD");
        setLocation(new java.awt.Point(185, 75));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("<html> <h2 align=\"center\">\nSELAMAT DATANG DI INTERFACE<br>MANAJEMEN PENGUNJUNG DENGAN RFID\n</h2> </html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Port Tersedia"));

        connectButton.setText("Connect");
        connectButton.setMinimumSize(new java.awt.Dimension(70, 23));
        connectButton.setPreferredSize(new java.awt.Dimension(70, 23));
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(portCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Date and Time"));

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        timeLabel.setText("00:00:00");

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateLabel.setText("Sabtu, 7 April 2018");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("MENDAFTAR KARTU BARU"));

        signButton.setText("Daftarkan!");
        signButton.setEnabled(false);
        signButton.setPreferredSize(new java.awt.Dimension(95, 30));
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });

        roleCombo.setPreferredSize(new java.awt.Dimension(95, 30));

        jLabel6.setText("Pilih role kartu:");

        namaText.setToolTipText("Nama pemegang tag");
        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama Pemilik Tag:");

        NUIDText.setForeground(new java.awt.Color(0, 255, 0));
        NUIDText.setText("NUID");
        NUIDText.setToolTipText("NUID Terdeteksi");
        NUIDText.setEnabled(false);
        NUIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUIDTextActionPerformed(evt);
            }
        });

        scanButton.setText("Scan");
        scanButton.setEnabled(false);
        scanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanButtonActionPerformed(evt);
            }
        });

        identitasText.setToolTipText("Nama pemegang tag");
        identitasText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identitasTextActionPerformed(evt);
            }
        });

        jLabel10.setText("Nomor Identitas:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(signButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(identitasText)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(NUIDText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scanButton))
                            .addComponent(roleCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identitasText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dumpButton.setText("Lihat Admin");
        dumpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dumpButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("MANAGE SISTEM"));

        authorButton.setText("Atur Autorisasi");
        authorButton.setPreferredSize(new java.awt.Dimension(150, 40));
        authorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorButtonActionPerformed(evt);
            }
        });

        logButton.setText("Log Aktivitas");
        logButton.setPreferredSize(new java.awt.Dimension(150, 40));
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        roleButton.setText("Role dan Ruangan");
        roleButton.setPreferredSize(new java.awt.Dimension(150, 40));
        roleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleButtonActionPerformed(evt);
            }
        });

        taglistButton.setText("Daftar Tag");
        taglistButton.setPreferredSize(new java.awt.Dimension(150, 40));
        taglistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taglistButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(authorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(roleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(taglistButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taglistButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registerButton.setText("Register Admin");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("MANAGE KARTU"));

        statusButton.setText("Cek Status");
        statusButton.setEnabled(false);
        statusButton.setMinimumSize(new java.awt.Dimension(127, 50));
        statusButton.setPreferredSize(new java.awt.Dimension(150, 40));
        statusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset Kartu");
        resetButton.setEnabled(false);
        resetButton.setMinimumSize(new java.awt.Dimension(127, 50));
        resetButton.setPreferredSize(new java.awt.Dimension(150, 40));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        scanButton2.setText("Scan");
        scanButton2.setEnabled(false);
        scanButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanButton2ActionPerformed(evt);
            }
        });

        NUIDText2.setForeground(new java.awt.Color(0, 255, 0));
        NUIDText2.setText("NUID");
        NUIDText2.setToolTipText("NUID Terdeteksi");
        NUIDText2.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(NUIDText2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scanButton2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(statusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUIDText2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dumpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(logoutButton)
                    .addComponent(dumpButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void scanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanButtonActionPerformed
        // TODO add your handling code here:        
        readData="";
        serial.resetReadPointer();
        if(scanButton.getText().equals("Scan") && port.isOpen()){
            serial.writeData("0");
            readData = serial.readByClick();            
        }
        else{
            scanButton.setText("Scan");
        }
        this.NUIDText.setText(readData);
        if(readData.length() > 7){
            this.signButton.setEnabled(true);
        }
        else{
            this.signButton.setEnabled(false);
        }
    }//GEN-LAST:event_scanButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:        
        if(connectButton.getText().equals("Connect")) {
            //mencoba koneksi ke serial port
            port = SerialPort.getCommPort(comm.get(portCombo.getSelectedIndex()).getData());
            serial = new SerialConn(port);
            if(serial.connectPort()) {
                connectButton.setText("Disconnect");
                portCombo.setEnabled(false);
                scanButton.setEnabled(true);
                scanButton2.setEnabled(true);
            }
        }        
        else {
                // disconnect from the serial port
                port.closePort();
                portCombo.setEnabled(true);
                connectButton.setText("Connect");
                System.out.println("Koneksi diputus");
                scanButton.setEnabled(false);
                scanButton2.setEnabled(false);
        }
    }//GEN-LAST:event_connectButtonActionPerformed
    
    private void statusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtonActionPerformed
        // TODO add your handling code here:
        String NUID = this.NUIDText2.getText();
        serial.writeData("2");
        String data = serial.readByClick();
        data = new Blowfish(data, NUID).getDecrypt();
        System.out.println(data);
        
        try{            
            rs = new FungsiQuery().selectData("*", "daftar_tag JOIN daftar_role USING (id_role)", "NUID = '" + NUID + "'");            
            if(rs.next()){
                String role = rs.getString("nama_role");
                String nama = rs.getString("nama_pemilik");
                JOptionPane.showMessageDialog(this, data + "\n" + nama + "\n" + role, "Informasi Kartu", JOptionPane.INFORMATION_MESSAGE);
            }            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_statusButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        String NUID = this.NUIDText2.getText();
        serial.writeData("1   #");
        if(serial.readByClick().contains("success")){
            if(new FungsiQuery().deleteData("daftar_tag", "NUID = '" + NUID + "'")){
                new LogReport().report("RMTAG", nama_admin, NUID, null);
            }
            JOptionPane.showMessageDialog(this, "Berhasil hapus NUID " + NUID);            
        }
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginPage l = new LoginPage();
        l.setVisible(true);
        port.closePort();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void authorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorButtonActionPerformed
        // TODO add your handling code here:
        AuthorPage auth = new AuthorPage();
        auth.getNamaAdmin(nama_admin);
        auth.setVisible(true);
    }//GEN-LAST:event_authorButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
       // TODO add your handling code here:
       LogAktivitas log = new LogAktivitas();
       log.setVisible(true);
    }//GEN-LAST:event_logButtonActionPerformed

    private void NUIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUIDTextActionPerformed
    
    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        // TODO add your handling code here
        //melakukan error checking
        if(namaText.getText().length() < 3){
                JOptionPane.showMessageDialog(null, "Nama minimal 3 karakter!", "Gagal", JOptionPane.ERROR_MESSAGE);
                return;
            }
        if(identitasText.getText().length() < 5){
                JOptionPane.showMessageDialog(null, "Nomor identitas minimal 5 karakter!", "Gagal", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //mengecek apakah NUID sudah terdaftar
            try{
                rs = new FungsiQuery().selectData("*", "daftar_tag", "NUID = '" + this.NUIDText.getText() + "'");
                if(rs.next()){
                    int answer = JOptionPane.showConfirmDialog(this, "Ganti data dengan yang baru?", "Data Lama Masih Tersimpan", JOptionPane.YES_NO_OPTION);
                    if(answer == 0){
                        new LogReport().report("CHOWN", nama_admin, this.NUIDText.getText(), "");
                        new FungsiQuery().deleteData("daftar_tag", "NUID = '" + this.NUIDText.getText() + "'");
                    }
                    else
                        return;
                }
            }
            catch(SQLException e){
                System.out.println(e.getMessage());
            }
        
        //mencoba menulis data ke tag
        String roleid = role.get(this.roleCombo.getSelectedIndex()).getId();
        String paket = new Blowfish(roleid + "-" + this.identitasText.getText(), this.NUIDText.getText()).getEncrypt();
        System.out.println("Menulis " + paket + "#");
        serial.sendData("1" + paket + "#");
        if(!serial.readByClick().contains("success")){
            JOptionPane.showMessageDialog(null, "Harap tempelkan kartu ke perangkat saat proses mendaftar!", "Gagal menulis data", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            //mengenkripsi data nomor identitas
            String id = new Blowfish(this.identitasText.getText(), this.NUIDText.getText()).getEncrypt();            
            //      menambahkan data tag ke database         
            if(new FungsiQuery().addData("`daftar_tag`", "`NUID`, `status_aktif`, `status_ruang`, `id_role`, `nama_pemilik`, `no_identitas`",
                    "'"+ this.NUIDText.getText() + "','1', '0','" + role.get(this.roleCombo.getSelectedIndex()).getId()+"', '" + this.namaText.getText()+"','"
                            + id + "'")){
                //mereset field setelah query berhasil
                this.namaText.setText("");
                this.identitasText.setText("");
                this.NUIDText.setText("NUID");
                this.signButton.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Berhasil didaftarkan");
                new LogReport().report("ADDTAG", nama_admin, NUIDText.getText(), null);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_signButtonActionPerformed

    private void roleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleButtonActionPerformed
        // TODO add your handling code here:
        RoleRuanganPage rr = new RoleRuanganPage();
        rr.getNamaAdmin(nama_admin);
        rr.setVisible(true);        
    }//GEN-LAST:event_roleButtonActionPerformed

    private void taglistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taglistButtonActionPerformed
        // TODO add your handling code here:
        TagPage tag = new TagPage();
        tag.setVisible(true);
    }//GEN-LAST:event_taglistButtonActionPerformed

    private void identitasTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identitasTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identitasTextActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        RegisterPage reg = new RegisterPage(nama_admin);
        reg.setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void scanButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanButton2ActionPerformed
        // TODO add your handling code here:
        readData="";
        serial.resetReadPointer();
        if(port.isOpen()){
            serial.writeData("0");
            readData = serial.readByClick();            
        }
        this.NUIDText2.setText(readData);
        if(readData.length() > 7){
            this.resetButton.setEnabled(true);
            this.statusButton.setEnabled(true);
        }
    }//GEN-LAST:event_scanButton2ActionPerformed

    private void dumpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dumpButtonActionPerformed
        // TODO add your handling code here:        
        ListAdmin adm = new ListAdmin();
        adm.getNamaAdmin(nama_admin);
        adm.setVisible(true);
    }//GEN-LAST:event_dumpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NUIDText;
    private javax.swing.JTextField NUIDText2;
    private javax.swing.JButton authorButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton dumpButton;
    private javax.swing.JTextField identitasText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField namaText;
    private javax.swing.JComboBox<String> portCombo;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton roleButton;
    private javax.swing.JComboBox<String> roleCombo;
    public javax.swing.JButton scanButton;
    public javax.swing.JButton scanButton2;
    private javax.swing.JButton signButton;
    private javax.swing.JButton statusButton;
    private javax.swing.JButton taglistButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
