/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitorgui;
import tools.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import koneksi_db_comm.koneksi_db;
import tools.FungsiQuery;

/**
 *
 * @author Anggun Dwiguna
 */
public class RoleRuanganPage extends javax.swing.JFrame {

    /**
     * Creates new form RolePage
     */
    String nama_admin;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    ArrayList<Vardump> role = new ArrayList();
    ArrayList<Vardump> ruangan = new ArrayList();
    
    public RoleRuanganPage() {
        initComponents();
        refreshList();        
        koneksi_db.config();
        con = koneksi_db.con;
        stat = koneksi_db.stm;        
    }
    
    public void getNamaAdmin(String admin){
        nama_admin = admin;
    }
    
    public void refreshList(){
        try{
            //seleksi daftar role
            rs = new FungsiQuery().selectData("*", "daftar_role", "1");
            DefaultListModel dlml = new DefaultListModel();
            role.clear();
            while(rs.next()){
                dlml.addElement(rs.getString("nama_role"));
                Vardump r = new Vardump();
                r.setData(rs.getString("id_role"), rs.getString("nama_role"));
                role.add(r);
            }
            roleList.setModel(dlml);
            
            //seleksi daftar ruangan
            rs = new FungsiQuery().selectData("*", "daftar_ruangan", "1");
            DefaultListModel dlmr = new DefaultListModel();
            ruangan.clear();
            while(rs.next()){
                dlmr.addElement(rs.getString("nama_ruangan") + "(" + rs.getString("id_ruangan") + ")");
                Vardump r = new Vardump();
                r.setData(rs.getString("id_ruangan"), rs.getString("nama_ruangan"));
                ruangan.add(r);
            }
            ruanganList.setModel(dlmr);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    HomePage obj;
    public void passObject(HomePage h){
        obj = h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        roleText = new javax.swing.JTextField();
        addRole = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ruanganText = new javax.swing.JTextField();
        addRuangan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roleList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ruanganList = new javax.swing.JList<>();
        delete1Button = new javax.swing.JButton();
        rename1Button = new javax.swing.JButton();
        rename2Button = new javax.swing.JButton();
        delete2Button = new javax.swing.JButton();
        roleRename = new javax.swing.JTextField();
        ruanganRename = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Role dan Ruangan");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah Role Baru"));

        addRole.setText("Tambah");
        addRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoleActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Role");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(roleText, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRole, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roleText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah Ruangan Baru"));

        addRuangan.setText("Tambah");
        addRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRuanganActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama Ruangan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ruanganText, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addRuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ruanganText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANAGE ROLE DAN RUANGAN");

        roleList.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Role"));
        jScrollPane1.setViewportView(roleList);

        ruanganList.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Ruangan"));
        jScrollPane2.setViewportView(ruanganList);

        delete1Button.setText("Delete");
        delete1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ButtonActionPerformed(evt);
            }
        });

        rename1Button.setText("Rename");
        rename1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rename1ButtonActionPerformed(evt);
            }
        });

        rename2Button.setText("Rename");
        rename2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rename2ButtonActionPerformed(evt);
            }
        });

        delete2Button.setText("Delete");
        delete2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roleRename, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rename1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete1Button))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ruanganRename, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rename2Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete2Button)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete1Button)
                    .addComponent(rename1Button)
                    .addComponent(delete2Button)
                    .addComponent(rename2Button)
                    .addComponent(roleRename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruanganRename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoleActionPerformed
        // TODO add your handling code here:
        try{
            if(new FungsiQuery().addData("daftar_role", "id_role, nama_role", "NULL,'"+this.roleText.getText()+"'")){
                JOptionPane.showMessageDialog(this, "Berhasil menambah role baru");
                new LogReport().report("ADDROLE", nama_admin, roleText.getText(), null);
                this.roleText.setText("");
            }
            refreshList();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }//GEN-LAST:event_addRoleActionPerformed

    private void addRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRuanganActionPerformed
        // TODO add your handling code here:
        try{
            if(new FungsiQuery().addData("daftar_ruangan", "id_ruangan, nama_ruangan", "NULL,'"+this.ruanganText.getText()+"'")){
                JOptionPane.showMessageDialog(this, "Berhasil menambah ruangan baru");
                this.ruanganText.setText("");
                new LogReport().report("ADDROOM", nama_admin, ruanganText.getText(), null);
            }
            refreshList();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }//GEN-LAST:event_addRuanganActionPerformed

    private void delete2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ButtonActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Anda yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION)==0){
            int[] selects = this.ruanganList.getSelectedIndices();
            for(int select: selects){                
                new FungsiQuery().deleteData("daftar_ruangan", "nama_ruangan ='" + ruangan.get(select).getData() + "'");
                new FungsiQuery().deleteData("daftar_hakakses", "id_ruangan ='" + ruangan.get(select).getId()+"'");                
            }
            JOptionPane.showMessageDialog(null, "Berhasil hapus!");
            new LogReport().report("RMROOM", nama_admin, ruanganList.getSelectedValue(), null);
            refreshList();
        }
    }//GEN-LAST:event_delete2ButtonActionPerformed

    private void rename1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rename1ButtonActionPerformed
        // TODO add your handling code here:
        if(roleList.getSelectedValues().length != 1){
            JOptionPane.showMessageDialog(this, "Silahkan pilih satu item untuk rename!");
        }
        else if((roleRename.getText().length() < 3)||(this.roleRename.getText().equals(this.roleList.getSelectedValue()))){
            JOptionPane.showMessageDialog(this, "Silahkan beri nama baru minimal 3 karakter!");
        }
        else{
            int index = this.roleList.getSelectedIndex();
            if(new FungsiQuery().updateData("daftar_role", "nama_role = '" +this.roleRename.getText()+ "'", "id_role='" + role.get(index).getId() +"'")){
                JOptionPane.showMessageDialog(this, "Berhasil rename!");
                new LogReport().report("CHROLE", nama_admin, this.roleRename.getText(), null);
                refreshList();                
            }
            this.roleRename.setText("");
        }
    }//GEN-LAST:event_rename1ButtonActionPerformed

    private void delete1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ButtonActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Anda yakin?", "Konfirmasi", JOptionPane.YES_NO_OPTION)==0){
            int[] selects = this.roleList.getSelectedIndices();
            for(int select: selects){
                
                new FungsiQuery().deleteData("daftar_role", "nama_role ='" + role.get(select).getData() + "'");
                new FungsiQuery().deleteData("daftar_hakakses", "id_role ='" + role.get(select).getId()+"'");                
            }
            JOptionPane.showMessageDialog(null, "Berhasil hapus!");
            new LogReport().report("RMROLE", nama_admin, roleList.getSelectedValue(), null);
            refreshList();
        }
    }//GEN-LAST:event_delete1ButtonActionPerformed

    private void rename2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rename2ButtonActionPerformed
        // TODO add your handling code here:
        if(ruanganList.getSelectedValues().length != 1){
            JOptionPane.showMessageDialog(this, "Silahkan pilih satu item untuk rename!");
        }
        else if((ruanganRename.getText().length() < 3)||(ruanganRename.getText().equals(this.ruanganList.getSelectedValue()))){
            JOptionPane.showMessageDialog(this, "Silahkan beri nama baru minimal 3 karakter!");
        }
        else{
            int index = this.ruanganList.getSelectedIndex();
            if(new FungsiQuery().updateData("daftar_ruangan", "nama_ruangan = '" +this.ruanganRename.getText()+ "'", "id_ruangan='" + ruangan.get(index).getId() +"'")){
                JOptionPane.showMessageDialog(this, "Berhasil rename!");
                new LogReport().report("CHROOM", nama_admin, this.ruanganRename.getText(), null);
                refreshList();
            }
            this.ruanganRename.setText("");
        }
    }//GEN-LAST:event_rename2ButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        obj.refreshList();        
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoleRuanganPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoleRuanganPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoleRuanganPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoleRuanganPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoleRuanganPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRole;
    private javax.swing.JButton addRuangan;
    private javax.swing.JButton delete1Button;
    private javax.swing.JButton delete2Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rename1Button;
    private javax.swing.JButton rename2Button;
    private javax.swing.JList<String> roleList;
    private javax.swing.JTextField roleRename;
    private javax.swing.JTextField roleText;
    private javax.swing.JList<String> ruanganList;
    private javax.swing.JTextField ruanganRename;
    private javax.swing.JTextField ruanganText;
    // End of variables declaration//GEN-END:variables
}
